pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true

- task: CmdLine@2
  displayName: 'build'
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    

- task: CmdLine@2
  displayName: 'Unit Test'
  inputs:
    script: 'npm run test-ci'
    
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'cacevedod'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1
  displayName: 'Análisis de código estático'

- task: SonarCloudPublish@1
  displayName: 'Quality Gate'
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-cuentapoc'
    regionName: 'us-east-1'
    bucketName: 'cacevedod-udem2-petbook'
    globExpressions: '*.zip'
    targetFolder: 'artefactos'
    createBucket: true