pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true

- task: CmdLine@2
  displayName: 'build'
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    

- task: CmdLine@2
  displayName: 'Unit Test'
  inputs:
    script: 'npm run test-ci'